apiVersion: v1
kind: Secret
metadata:
  name: linebot-document-secrets
type: Opaque
stringData:
  database-password: REPLACE_ME
  object-storage-access-key: REPLACE_OR_REMOVE_FOR_IAM
  object-storage-secret-key: REPLACE_OR_REMOVE_FOR_IAM
  line-channel-token: REPLACE_ME
  line-channel-secret: REPLACE_ME
  admin-token: REPLACE_WITH_AT_LEAST_32_CHARACTERS
  assets-sync-token: REPLACE_ME
