apiVersion: v1
kind: Service
metadata:
  name: linebot-document
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: linebot-document
  ports:
    - name: http
      port: 80
      targetPort: http

